cantcola = int(input("Cuantas Coca Colas has vendido:\n"))
cantfanta = int(input("Cuantas Fantas has vendido:\n"))
cantlimon = int(input("Cuantas Limonadas has vendido:\n"))
preucola = int(input("A que precio has vendido cada Coca Cola:\n"))
preufanta = int(input("A que precio has vendido cada Fanta:\n"))
preulimon = int(input("A que precio has vendido cada Limonada:\n"))
print("Coca Cola" , cantcola , "ud" , preucola, "€/un" , cantcola * preucola , "€") 
print("Fanta" , cantfanta , "ud" , preufanta, "€/un" , cantfanta * preufanta , "€") 
print("Limonada" , cantlimon , "ud" , preulimon , "€/un" , cantlimon * preulimon , "€")
print("Total:" , cantcola * preucola + cantfanta * preufanta + cantlimon * preulimon , "€")